[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
rayon = "1.10.0"
rustc-hash = "2.1.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
colored = "2.1.0"
